### PR TITLE
Fix hansard parsing

### PR DESCRIPTION
**Pull request by jbothma**
This PR will allow a hansard's date to be on another paragraph other than the very first paragraph in the document (which we previously assumed would always be the case).

This PR should fix the `DateParseException` that was raised when the date wasn't on the first line of the document. Since the exception was raised, the `Source`'s `last_processing_success` field would still be `None`. So if we run the `./manage.py za_hansard_run_parsing` script with the `--retry` option, the `Source` which had this issue will be re-parsed.

I updated one of the test documents to move its date lower down in the document. There are still test documents [left over](https://github.com/OpenUpSA/pombola/tree/master/pombola/za_hansard/tests/test_inputs/hansard) that still cater for the case when the date is on the first line of the document.

[Pivotal](https://www.pivotaltracker.com/n/projects/2397264/stories/170743497)

### CODE REVIEW

**Comment by jbothma** [comment]
We need test cases covering the different formats files can take, so just changing the file is not sufficient.

I hoped this could be done with a unit test but it looks like it's more of an integration test of the parser bits since we're changing behaviour of the parser as a whole.

I think we need 

- the current test
- a test verifying that your exception is raised if a date is not found (another document)
  - this can be small, right? just add a file to the list and check for an exception? It might need to be a different class since it will fail when setUp calls process, won't it?
- a test verifying that the date can be where it used to be
  - this can small - it just needs to verify the date part and perhaps one other thing? not sure if it needs to verify something before or after the date to be more valid.

**Comment by deanmalan** [comment]
@jbothma not sure if I understand the third case. The `ZAHansardParsingTests` class tests [multiple](https://github.com/OpenUpSA/pombola/pull/5/files#diff-b932a966ac1e0dc4a82f45e6d20eaa58R26) documents and I only changed one of them to have the date in the new position. There are still other documents left that have the date at its old position (i.e. first line in the document). Do I need to add more documents or do you mean a different type of test needs to be added?

**Comment by jbothma** [comment]
> @jbothma not sure if I understand the third case. The `ZAHansardParsingTests` class tests [multiple](https://github.com/OpenUpSA/pombola/pull/5/files#diff-b932a966ac1e0dc4a82f45e6d20eaa58R26) documents and I only changed one of them to have the date in the new position. There are still other documents left that have the date at its old position (i.e. first line in the document). Do I need to add more documents or do you mean a different type of test needs to be added?

Oh of course! ok, cool - no it's fine then - then we just want a test hitting that date exception which I think you've done - checking quick

**Comment by jbothma** [comment]
> @jbothma not sure if I understand the third case. The `ZAHansardParsingTests` class tests [multiple](https://github.com/OpenUpSA/pombola/pull/5/files#diff-b932a966ac1e0dc4a82f45e6d20eaa58R26) documents and I only changed one of them to have the date in the new position. There are still other documents left that have the date at its old position (i.e. first line in the document). Do I need to add more documents or do you mean a different type of test needs to be added?

Oh of course! ok, cool - no it's fine then.

Ship it!

**Comment by jbothma** [comment]
> @jbothma not sure if I understand the third case. The `ZAHansardParsingTests` class tests [multiple](https://github.com/OpenUpSA/pombola/pull/5/files#diff-b932a966ac1e0dc4a82f45e6d20eaa58R26) documents and I only changed one of them to have the date in the new position. There are still other documents left that have the date at its old position (i.e. first line in the document). Do I need to add more documents or do you mean a different type of test needs to be added?

Oh of course! ok, cool - no it's fine then.

Ship it!

**Comment by jbothma** [comment]
> @jbothma not sure if I understand the third case. The `ZAHansardParsingTests` class tests [multiple](https://github.com/OpenUpSA/pombola/pull/5/files#diff-b932a966ac1e0dc4a82f45e6d20eaa58R26) documents and I only changed one of them to have the date in the new position. There are still other documents left that have the date at its old position (i.e. first line in the document). Do I need to add more documents or do you mean a different type of test needs to be added?

Oh of course! ok, cool - no it's fine then.

Ship it!

**Pull request merged**
